language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages

