language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages

